//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
// 
#pragma warning disable 1591

namespace EcommerceLibrary.HotelService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="HotelServiceSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(object[]))]
    public partial class HotelService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetHotelsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRoomsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRoomsByAmenitiesOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReserveOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public HotelService() {
            this.Url = global::EcommerceLibrary.Properties.Settings.Default.EcommerceLibrary_HotelService_HotelService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetHotelsCompletedEventHandler GetHotelsCompleted;
        
        /// <remarks/>
        public event GetRoomsCompletedEventHandler GetRoomsCompleted;
        
        /// <remarks/>
        public event GetRoomsByAmenitiesCompletedEventHandler GetRoomsByAmenitiesCompleted;
        
        /// <remarks/>
        public event ReserveCompletedEventHandler ReserveCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetHotels", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetHotels(string city, string state) {
            object[] results = this.Invoke("GetHotels", new object[] {
                        city,
                        state});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetHotelsAsync(string city, string state) {
            this.GetHotelsAsync(city, state, null);
        }
        
        /// <remarks/>
        public void GetHotelsAsync(string city, string state, object userState) {
            if ((this.GetHotelsOperationCompleted == null)) {
                this.GetHotelsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetHotelsOperationCompleted);
            }
            this.InvokeAsync("GetHotels", new object[] {
                        city,
                        state}, this.GetHotelsOperationCompleted, userState);
        }
        
        private void OnGetHotelsOperationCompleted(object arg) {
            if ((this.GetHotelsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetHotelsCompleted(this, new GetHotelsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRooms", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetRooms(Hotel hotel) {
            object[] results = this.Invoke("GetRooms", new object[] {
                        hotel});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetRoomsAsync(Hotel hotel) {
            this.GetRoomsAsync(hotel, null);
        }
        
        /// <remarks/>
        public void GetRoomsAsync(Hotel hotel, object userState) {
            if ((this.GetRoomsOperationCompleted == null)) {
                this.GetRoomsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRoomsOperationCompleted);
            }
            this.InvokeAsync("GetRooms", new object[] {
                        hotel}, this.GetRoomsOperationCompleted, userState);
        }
        
        private void OnGetRoomsOperationCompleted(object arg) {
            if ((this.GetRoomsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRoomsCompleted(this, new GetRoomsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRoomsByAmenities", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetRoomsByAmenities(Amenities amenitities, string city, string state) {
            object[] results = this.Invoke("GetRoomsByAmenities", new object[] {
                        amenitities,
                        city,
                        state});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetRoomsByAmenitiesAsync(Amenities amenitities, string city, string state) {
            this.GetRoomsByAmenitiesAsync(amenitities, city, state, null);
        }
        
        /// <remarks/>
        public void GetRoomsByAmenitiesAsync(Amenities amenitities, string city, string state, object userState) {
            if ((this.GetRoomsByAmenitiesOperationCompleted == null)) {
                this.GetRoomsByAmenitiesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRoomsByAmenitiesOperationCompleted);
            }
            this.InvokeAsync("GetRoomsByAmenities", new object[] {
                        amenitities,
                        city,
                        state}, this.GetRoomsByAmenitiesOperationCompleted, userState);
        }
        
        private void OnGetRoomsByAmenitiesOperationCompleted(object arg) {
            if ((this.GetRoomsByAmenitiesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRoomsByAmenitiesCompleted(this, new GetRoomsByAmenitiesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Reserve", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Reserve(Room room, Customer customer) {
            object[] results = this.Invoke("Reserve", new object[] {
                        room,
                        customer});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ReserveAsync(Room room, Customer customer) {
            this.ReserveAsync(room, customer, null);
        }
        
        /// <remarks/>
        public void ReserveAsync(Room room, Customer customer, object userState) {
            if ((this.ReserveOperationCompleted == null)) {
                this.ReserveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReserveOperationCompleted);
            }
            this.InvokeAsync("Reserve", new object[] {
                        room,
                        customer}, this.ReserveOperationCompleted, userState);
        }
        
        private void OnReserveOperationCompleted(object arg) {
            if ((this.ReserveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReserveCompleted(this, new ReserveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Hotel {
        
        private string nameField;
        
        private string addressField;
        
        private string cityField;
        
        private string stateField;
        
        private int idField;
        
        private int zipField;
        
        private int numOfPoolsField;
        
        private int numOfBarsField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int Zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
            }
        }
        
        /// <remarks/>
        public int NumOfPools {
            get {
                return this.numOfPoolsField;
            }
            set {
                this.numOfPoolsField = value;
            }
        }
        
        /// <remarks/>
        public int NumOfBars {
            get {
                return this.numOfBarsField;
            }
            set {
                this.numOfBarsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Customer {
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string addressField;
        
        private string cityField;
        
        private string stateField;
        
        private int zipField;
        
        private int custIDField;
        
        private int creditCardNumField;
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public int Zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
            }
        }
        
        /// <remarks/>
        public int CustID {
            get {
                return this.custIDField;
            }
            set {
                this.custIDField = value;
            }
        }
        
        /// <remarks/>
        public int CreditCardNum {
            get {
                return this.creditCardNumField;
            }
            set {
                this.creditCardNumField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Room {
        
        private int roomNumberField;
        
        private int numOfBathroomsField;
        
        private int numOfBedsField;
        
        private int roomIDField;
        
        private int priceField;
        
        private object[] amenitiesField;
        
        private bool reservedField;
        
        /// <remarks/>
        public int RoomNumber {
            get {
                return this.roomNumberField;
            }
            set {
                this.roomNumberField = value;
            }
        }
        
        /// <remarks/>
        public int NumOfBathrooms {
            get {
                return this.numOfBathroomsField;
            }
            set {
                this.numOfBathroomsField = value;
            }
        }
        
        /// <remarks/>
        public int NumOfBeds {
            get {
                return this.numOfBedsField;
            }
            set {
                this.numOfBedsField = value;
            }
        }
        
        /// <remarks/>
        public int RoomID {
            get {
                return this.roomIDField;
            }
            set {
                this.roomIDField = value;
            }
        }
        
        /// <remarks/>
        public int Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        public object[] Amenities {
            get {
                return this.amenitiesField;
            }
            set {
                this.amenitiesField = value;
            }
        }
        
        /// <remarks/>
        public bool Reserved {
            get {
                return this.reservedField;
            }
            set {
                this.reservedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Amenities {
        
        private int wifiField;
        
        private int smokingField;
        
        private int valetParkingField;
        
        private int gymField;
        
        private int poolsideBarField;
        
        private int freeBreakfastField;
        
        /// <remarks/>
        public int Wifi {
            get {
                return this.wifiField;
            }
            set {
                this.wifiField = value;
            }
        }
        
        /// <remarks/>
        public int Smoking {
            get {
                return this.smokingField;
            }
            set {
                this.smokingField = value;
            }
        }
        
        /// <remarks/>
        public int ValetParking {
            get {
                return this.valetParkingField;
            }
            set {
                this.valetParkingField = value;
            }
        }
        
        /// <remarks/>
        public int Gym {
            get {
                return this.gymField;
            }
            set {
                this.gymField = value;
            }
        }
        
        /// <remarks/>
        public int PoolsideBar {
            get {
                return this.poolsideBarField;
            }
            set {
                this.poolsideBarField = value;
            }
        }
        
        /// <remarks/>
        public int FreeBreakfast {
            get {
                return this.freeBreakfastField;
            }
            set {
                this.freeBreakfastField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetHotelsCompletedEventHandler(object sender, GetHotelsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetHotelsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetHotelsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetRoomsCompletedEventHandler(object sender, GetRoomsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRoomsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRoomsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetRoomsByAmenitiesCompletedEventHandler(object sender, GetRoomsByAmenitiesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRoomsByAmenitiesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRoomsByAmenitiesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ReserveCompletedEventHandler(object sender, ReserveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReserveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReserveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591