//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
// 
#pragma warning disable 1591

namespace EcommerceLibrary.CarService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CarWebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class CarWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetRentalCarAgenciesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCarsOperationCompleted;
        
        private System.Threading.SendOrPostCallback FindCarsOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReserveOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CarWebService() {
            this.Url = global::EcommerceLibrary.Properties.Settings.Default.EcommerceLibrary_CarService_CarWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetRentalCarAgenciesCompletedEventHandler GetRentalCarAgenciesCompleted;
        
        /// <remarks/>
        public event GetCarsCompletedEventHandler GetCarsCompleted;
        
        /// <remarks/>
        public event FindCarsCompletedEventHandler FindCarsCompleted;
        
        /// <remarks/>
        public event ReserveCompletedEventHandler ReserveCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRentalCarAgencies", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetRentalCarAgencies(string city, string state) {
            object[] results = this.Invoke("GetRentalCarAgencies", new object[] {
                        city,
                        state});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetRentalCarAgenciesAsync(string city, string state) {
            this.GetRentalCarAgenciesAsync(city, state, null);
        }
        
        /// <remarks/>
        public void GetRentalCarAgenciesAsync(string city, string state, object userState) {
            if ((this.GetRentalCarAgenciesOperationCompleted == null)) {
                this.GetRentalCarAgenciesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRentalCarAgenciesOperationCompleted);
            }
            this.InvokeAsync("GetRentalCarAgencies", new object[] {
                        city,
                        state}, this.GetRentalCarAgenciesOperationCompleted, userState);
        }
        
        private void OnGetRentalCarAgenciesOperationCompleted(object arg) {
            if ((this.GetRentalCarAgenciesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRentalCarAgenciesCompleted(this, new GetRentalCarAgenciesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCars", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetCars(Agency curAgency, string city, string state) {
            object[] results = this.Invoke("GetCars", new object[] {
                        curAgency,
                        city,
                        state});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetCarsAsync(Agency curAgency, string city, string state) {
            this.GetCarsAsync(curAgency, city, state, null);
        }
        
        /// <remarks/>
        public void GetCarsAsync(Agency curAgency, string city, string state, object userState) {
            if ((this.GetCarsOperationCompleted == null)) {
                this.GetCarsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCarsOperationCompleted);
            }
            this.InvokeAsync("GetCars", new object[] {
                        curAgency,
                        city,
                        state}, this.GetCarsOperationCompleted, userState);
        }
        
        private void OnGetCarsOperationCompleted(object arg) {
            if ((this.GetCarsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCarsCompleted(this, new GetCarsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FindCars", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet FindCars(Requirements Requirements, string City, string State) {
            object[] results = this.Invoke("FindCars", new object[] {
                        Requirements,
                        City,
                        State});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void FindCarsAsync(Requirements Requirements, string City, string State) {
            this.FindCarsAsync(Requirements, City, State, null);
        }
        
        /// <remarks/>
        public void FindCarsAsync(Requirements Requirements, string City, string State, object userState) {
            if ((this.FindCarsOperationCompleted == null)) {
                this.FindCarsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFindCarsOperationCompleted);
            }
            this.InvokeAsync("FindCars", new object[] {
                        Requirements,
                        City,
                        State}, this.FindCarsOperationCompleted, userState);
        }
        
        private void OnFindCarsOperationCompleted(object arg) {
            if ((this.FindCarsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FindCarsCompleted(this, new FindCarsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Reserve", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Reserve(Car Car, Customer Customer) {
            object[] results = this.Invoke("Reserve", new object[] {
                        Car,
                        Customer});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ReserveAsync(Car Car, Customer Customer) {
            this.ReserveAsync(Car, Customer, null);
        }
        
        /// <remarks/>
        public void ReserveAsync(Car Car, Customer Customer, object userState) {
            if ((this.ReserveOperationCompleted == null)) {
                this.ReserveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReserveOperationCompleted);
            }
            this.InvokeAsync("Reserve", new object[] {
                        Car,
                        Customer}, this.ReserveOperationCompleted, userState);
        }
        
        private void OnReserveOperationCompleted(object arg) {
            if ((this.ReserveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReserveCompleted(this, new ReserveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Agency {
        
        private string agencyIDField;
        
        private string agencyNameField;
        
        private string agencyStreetAddressField;
        
        private string agencyCityField;
        
        private string agencyStateField;
        
        private string agencyZipField;
        
        private string agencyPhoneField;
        
        /// <remarks/>
        public string AgencyID {
            get {
                return this.agencyIDField;
            }
            set {
                this.agencyIDField = value;
            }
        }
        
        /// <remarks/>
        public string AgencyName {
            get {
                return this.agencyNameField;
            }
            set {
                this.agencyNameField = value;
            }
        }
        
        /// <remarks/>
        public string AgencyStreetAddress {
            get {
                return this.agencyStreetAddressField;
            }
            set {
                this.agencyStreetAddressField = value;
            }
        }
        
        /// <remarks/>
        public string AgencyCity {
            get {
                return this.agencyCityField;
            }
            set {
                this.agencyCityField = value;
            }
        }
        
        /// <remarks/>
        public string AgencyState {
            get {
                return this.agencyStateField;
            }
            set {
                this.agencyStateField = value;
            }
        }
        
        /// <remarks/>
        public string AgencyZip {
            get {
                return this.agencyZipField;
            }
            set {
                this.agencyZipField = value;
            }
        }
        
        /// <remarks/>
        public string AgencyPhone {
            get {
                return this.agencyPhoneField;
            }
            set {
                this.agencyPhoneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Customer {
        
        private int custIDField;
        
        private string custFirstNameField;
        
        private string custLastNameField;
        
        private string custStreetField;
        
        private string custCityField;
        
        private string custStateField;
        
        private string custZipField;
        
        private string custPhoneField;
        
        private string custEmailField;
        
        private string custCreditCardField;
        
        /// <remarks/>
        public int custID {
            get {
                return this.custIDField;
            }
            set {
                this.custIDField = value;
            }
        }
        
        /// <remarks/>
        public string custFirstName {
            get {
                return this.custFirstNameField;
            }
            set {
                this.custFirstNameField = value;
            }
        }
        
        /// <remarks/>
        public string custLastName {
            get {
                return this.custLastNameField;
            }
            set {
                this.custLastNameField = value;
            }
        }
        
        /// <remarks/>
        public string custStreet {
            get {
                return this.custStreetField;
            }
            set {
                this.custStreetField = value;
            }
        }
        
        /// <remarks/>
        public string custCity {
            get {
                return this.custCityField;
            }
            set {
                this.custCityField = value;
            }
        }
        
        /// <remarks/>
        public string custState {
            get {
                return this.custStateField;
            }
            set {
                this.custStateField = value;
            }
        }
        
        /// <remarks/>
        public string custZip {
            get {
                return this.custZipField;
            }
            set {
                this.custZipField = value;
            }
        }
        
        /// <remarks/>
        public string custPhone {
            get {
                return this.custPhoneField;
            }
            set {
                this.custPhoneField = value;
            }
        }
        
        /// <remarks/>
        public string custEmail {
            get {
                return this.custEmailField;
            }
            set {
                this.custEmailField = value;
            }
        }
        
        /// <remarks/>
        public string custCreditCard {
            get {
                return this.custCreditCardField;
            }
            set {
                this.custCreditCardField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Car {
        
        private int getCarIDField;
        
        private string getColorField;
        
        private string getMakeField;
        
        private string getnumberOfDoorsField;
        
        private string getTransmissionField;
        
        private string getHasNavigationField;
        
        private string getHasRearviewCameraField;
        
        private string getHasSunroofField;
        
        private string getYearMadeField;
        
        private string getCarTypeField;
        
        private string getIsAllWheelDriveField;
        
        private string getDailyRateField;
        
        private bool getIsAvailableField;
        
        /// <remarks/>
        public int GetCarID {
            get {
                return this.getCarIDField;
            }
            set {
                this.getCarIDField = value;
            }
        }
        
        /// <remarks/>
        public string GetColor {
            get {
                return this.getColorField;
            }
            set {
                this.getColorField = value;
            }
        }
        
        /// <remarks/>
        public string GetMake {
            get {
                return this.getMakeField;
            }
            set {
                this.getMakeField = value;
            }
        }
        
        /// <remarks/>
        public string GetnumberOfDoors {
            get {
                return this.getnumberOfDoorsField;
            }
            set {
                this.getnumberOfDoorsField = value;
            }
        }
        
        /// <remarks/>
        public string GetTransmission {
            get {
                return this.getTransmissionField;
            }
            set {
                this.getTransmissionField = value;
            }
        }
        
        /// <remarks/>
        public string GetHasNavigation {
            get {
                return this.getHasNavigationField;
            }
            set {
                this.getHasNavigationField = value;
            }
        }
        
        /// <remarks/>
        public string GetHasRearviewCamera {
            get {
                return this.getHasRearviewCameraField;
            }
            set {
                this.getHasRearviewCameraField = value;
            }
        }
        
        /// <remarks/>
        public string GetHasSunroof {
            get {
                return this.getHasSunroofField;
            }
            set {
                this.getHasSunroofField = value;
            }
        }
        
        /// <remarks/>
        public string GetYearMade {
            get {
                return this.getYearMadeField;
            }
            set {
                this.getYearMadeField = value;
            }
        }
        
        /// <remarks/>
        public string GetCarType {
            get {
                return this.getCarTypeField;
            }
            set {
                this.getCarTypeField = value;
            }
        }
        
        /// <remarks/>
        public string GetIsAllWheelDrive {
            get {
                return this.getIsAllWheelDriveField;
            }
            set {
                this.getIsAllWheelDriveField = value;
            }
        }
        
        /// <remarks/>
        public string GetDailyRate {
            get {
                return this.getDailyRateField;
            }
            set {
                this.getDailyRateField = value;
            }
        }
        
        /// <remarks/>
        public bool GetIsAvailable {
            get {
                return this.getIsAvailableField;
            }
            set {
                this.getIsAvailableField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Requirements {
        
        private string getColorField;
        
        private string getmakeField;
        
        private string getModelField;
        
        private string getnumberOfDoorsField;
        
        private string getTransmissionField;
        
        private string getHasNavigationField;
        
        private string getHasRearviewCameraField;
        
        private string getHasSunroofField;
        
        private string getYearMadeField;
        
        private string getCarTypeField;
        
        private string getIsAllWheelDriveField;
        
        /// <remarks/>
        public string GetColor {
            get {
                return this.getColorField;
            }
            set {
                this.getColorField = value;
            }
        }
        
        /// <remarks/>
        public string Getmake {
            get {
                return this.getmakeField;
            }
            set {
                this.getmakeField = value;
            }
        }
        
        /// <remarks/>
        public string GetModel {
            get {
                return this.getModelField;
            }
            set {
                this.getModelField = value;
            }
        }
        
        /// <remarks/>
        public string GetnumberOfDoors {
            get {
                return this.getnumberOfDoorsField;
            }
            set {
                this.getnumberOfDoorsField = value;
            }
        }
        
        /// <remarks/>
        public string GetTransmission {
            get {
                return this.getTransmissionField;
            }
            set {
                this.getTransmissionField = value;
            }
        }
        
        /// <remarks/>
        public string GetHasNavigation {
            get {
                return this.getHasNavigationField;
            }
            set {
                this.getHasNavigationField = value;
            }
        }
        
        /// <remarks/>
        public string GetHasRearviewCamera {
            get {
                return this.getHasRearviewCameraField;
            }
            set {
                this.getHasRearviewCameraField = value;
            }
        }
        
        /// <remarks/>
        public string GetHasSunroof {
            get {
                return this.getHasSunroofField;
            }
            set {
                this.getHasSunroofField = value;
            }
        }
        
        /// <remarks/>
        public string GetYearMade {
            get {
                return this.getYearMadeField;
            }
            set {
                this.getYearMadeField = value;
            }
        }
        
        /// <remarks/>
        public string GetCarType {
            get {
                return this.getCarTypeField;
            }
            set {
                this.getCarTypeField = value;
            }
        }
        
        /// <remarks/>
        public string GetIsAllWheelDrive {
            get {
                return this.getIsAllWheelDriveField;
            }
            set {
                this.getIsAllWheelDriveField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetRentalCarAgenciesCompletedEventHandler(object sender, GetRentalCarAgenciesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRentalCarAgenciesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRentalCarAgenciesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetCarsCompletedEventHandler(object sender, GetCarsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCarsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCarsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void FindCarsCompletedEventHandler(object sender, FindCarsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FindCarsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FindCarsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ReserveCompletedEventHandler(object sender, ReserveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReserveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReserveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591